from __future__ import annotations

from enum import StrEnum


class LogEvent(StrEnum):
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    PARSE_TASK_CREATED = "PARSE_TASK_CREATED"
    PARSE_TASK_FINISHED = "PARSE_TASK_FINISHED"
    PARSE_TASK_FAILED = "PARSE_TASK_FAILED"
    CASE_REVIEWED = "CASE_REVIEWED"
    EXECUTION_TASK_CREATED = "EXECUTION_TASK_CREATED"
    EXECUTION_TASK_STARTED = "EXECUTION_TASK_STARTED"
    EXECUTION_TASK_FINISHED = "EXECUTION_TASK_FINISHED"
    EXECUTION_TASK_FAILED = "EXECUTION_TASK_FAILED"
    CASE_EXECUTION_STARTED = "CASE_EXECUTION_STARTED"
    CASE_EXECUTION_FINISHED = "CASE_EXECUTION_FINISHED"
    STEP_EXECUTION_FINISHED = "STEP_EXECUTION_FINISHED"
    EVIDENCE_CAPTURED = "EVIDENCE_CAPTURED"
    EVIDENCE_CAPTURE_FAILED = "EVIDENCE_CAPTURE_FAILED"
