from __future__ import annotations

from typing import Protocol

from app.models import ExecutionCaseResult, ExecutionTask, ParseTask, ParsedTestCase, TaskLog, TestDocument


class AgentStore(Protocol):
    def save_document(self, document: TestDocument) -> TestDocument: ...

    def find_document(self, document_id: str) -> TestDocument | None: ...

    def save_parse_task(self, parse_task: ParseTask) -> ParseTask: ...

    def find_parse_task(self, parse_task_id: str) -> ParseTask | None: ...

    def save_parsed_cases(self, parse_task_id: str, cases: list[ParsedTestCase]) -> None: ...

    def find_parsed_cases(self, parse_task_id: str) -> list[ParsedTestCase]: ...

    def save_execution_task(self, task: ExecutionTask) -> ExecutionTask: ...

    def find_execution_task(self, task_id: str) -> ExecutionTask | None: ...

    def save_execution_cases(self, task_id: str, cases: list[ExecutionCaseResult]) -> None: ...

    def find_execution_cases(self, task_id: str) -> list[ExecutionCaseResult]: ...

    def add_log(self, log: TaskLog) -> None: ...

    def find_logs(self, task_id: str) -> list[TaskLog]: ...
